# COGS 118A- Project Checkpoint

# Names

Hopefully your team is at least this good. Obviously you should replace these with your names.

- Khalid Ade
- Pablo Moreno
- Sujay Srinivasan
- Daniel Vega Lojo
- Jared Chen

# Abstract 
<blockquote>
This section should be short and clearly stated. It should be a single paragraph < 200 words.  
                                                                                      
It should summarize: 
- what your goal/problem is
- what the data used represents and how they are measured
- what you will be doing with the data
- how performance/success will be measured
</blockquote>
    
    
    
    
    

Association Football (or soccer) is a worldwide sport played by over 250 million players in over 250 countries<sup><a name="note-assoc-football" href="#assoc-football">[1]</a></sup>.  In fact, football is the world’s sport, and the most popular across the globe in terms of fans as well. Football has a huge transfer market in which players are transferred across teams for up to hundreds of millions of euros. To put the amount of money that circulates in the global football market into perspective, squad values of top teams like Manchester United surpass billions of euros<sup><a name="note-transfermarkt-value-how" href="#transfermarkt-value-how">[2]</a></sup>. The market value of a player accounts for a huge role in how teams conduct their business in regards to transfers. Our goal is to help these clubs make the right investments in players they want to obtain, especially when spending huge amounts of money. More specifically, we want to accurately predict the market value of players so that clubs aren’t overpaying, or underselling their valued players. Plenty of factors play a role in determining the market value of a player. The most important factors include age, performance for club and national team (measured in stats such as goals, assists, tackles etc.) for a player in that position, experience(measured by number of seasons in top leagues), marketing value (measured by social media presence), and injury vulnerability<sup><a name="note-transfermarkt-value-how" href="#transfermarkt-value-how">[2]</a></sup>.

# Background

<blockquote>
Fill in the background and discuss the kind of prior work that has gone on in this research area here. **Use inline citation** to specify which references support which statements.  You can do that through HTML footnotes (demonstrated here). I used to reccommend Markdown footnotes (google is your friend) because they are simpler but recently I have had some problems with them working for me whereas HTML ones always work so far. So use the method that works for you, but do use inline citations.

Here is an example of inline citation. After government genocide in the 20th century, real birds were replaced with surveillance drones designed to look just like birds<a name="lorenz"></a>[<sup>[1]</sup>](#lorenznote). Use a minimum of 2 or 3 citations, but we prefer more <a name="admonish"></a>[<sup>[2]</sup>](#admonishnote). You need enough citations to fully explain and back up important facts. 

Remeber you are trying to explain why someone would want to answer your question or why your hypothesis is in the form that you've stated. 
</blockquote>






The global football transfer market involves the circulation of billions of euros. Many top European clubs have spent hundreds of millions of dollars to bolster their respective teams. For example teams like Manchester United, Manchester City, and PSG have spent almost billions of euros to sign players to help their teams’ success in their respective leagues and on the European stage<sup><a name="note-man-utd" href="#man-utd">[6]</a></sup>. There is no doubt that decisions involving huge sums of such money should be carefully analyzed so that clubs can maximize success in both the business side as well as the performance side of their respective clubs. Transfermarkt is an online platform for transfers, market values, rumors, and stats. The business model consists of, in addition to sports journalistic reporting, the profiles of the players and discussion forums on the performance and market values of individual soccer players, teams and leagues<sup><a name="note-ackermann-follert-etal" href="#ackermann-follert-etal">[4]</a></sup>. Frequently being discussed in sports science and sports economics literature over the past few years, the so-called "market values" („Marktwerte“) have so far seemed to become the center of media attention. Numerous studies have shown positive correlations between the predicted market values on Transfermarkt and the actual player income. It’s reportedly known that players who are in contract negotiations would sometimes refer to Transfermarkt values as baselines for their salary expectations<sup><a name="note-ackermann-follert-etal" href="#ackermann-follert-etal">[4]</a></sup>.  The “market values” can also be used as a measure of marketability; a higher marketability helps a player secure partnerships through sponsorship contracts. The age and performance statistics on Transfermarkt are also particularly useful in that player observers can identify young players and predict the development opportunities<sup><a name="note-ackermann-follert-etal" href="#ackermann-follert-etal">[4]</a></sup>. 

The open forums of Transfermarkt allow users to discuss and predict individual players’ market values and performance. Previous studies on collective intelligence<sup><a name="note-transfermarkt-value-how" href="#transfermarkt-value-how">[2]</a></sup> have used OLS regression models to evaluate the accuracy of predictions. It is shown that “forecasts of international soccer results based on the crowd’s valuations are more accurate than those based on standard predictors.”<sup><a name="note-peeters" href="#peeters">[3]</a></sup> This reveals a potential possibility that distributed intelligence is a contributing factor to the accuracy of predictions. We want to know if supervised machine learning algorithms, as another form of distributed intelligence, can make accurate predictions just as humans do. More particularly, we want to use machine learning models like OLS to predict market value of players across the football world.

# Problem Statement
<blockquote>
Clearly describe the problem that you are solving. Avoid ambiguous words. The problem described should be well defined and should have at least one ML-relevant potential solution. Additionally, describe the problem thoroughly such that it is clear that the problem is quantifiable (the problem can be expressed in mathematical or logical terms), measurable (the problem can be measured by some metric and clearly observed), and replicable (the problem can be reproduced and occurs more than once).
    
> In your problem statement, you could more clearly define exactly what problem you are trying to solve. Are you trying to predict the market value (in euros) of a player, e.g., how much a team is willing to pay for a player at a point in time?   
</blockquote>


Given the considerable number of players in football across the globe, it can get tedious to know which players have potential and are worth investing in. Do they have high performance for a player in their position? Are they playing for a renowned club or in a renowned league? Is their behavior respectable and are they marketable? These are the kinds of questions top clubs use when considering paying the big bucks for players. Our task is to identify the market value of players in global football using ML techniques such as least square regression and decision trees.

# Data

<blockquote>
UPDATED FROM PROPOSAL!

You should have obtained and cleaned (if necessary) data you will use for this project.

Please give the following infomration for each dataset you are using
- link/reference to obtain it
- description of the size of the dataset (# of variables, # of observations)
- what an observation consists of
- what some critical variables are, how they are represented
- any special handling, transformations, cleaning, etc you have done should be demonstrated here!
    
> Be careful when joining your data. I think there are better ways to join data than pandas syntax, e.g., sqlite, but you absolutely do not have to go that route. If you are curious, reach out to me.
</blockquote>

The dataset is composed of 7 different subsets, we will be using 4 of the datasets. Since each feature resides in different sets. <sup><a name="note-cariboo" href="#cariboo">[7]</a></sup> 

- `Appearances.csv`
    - Player ID, Game ID, Appearance ID, Competition ID, Player club ID, Assist, Minutes Played, Yellow cards, Red Cards
- `Clubs.csv `
    - Club ID, Name, Pretty_name, Domestic_competition_id, Total_market_value, Squad_size, Average_age, Foreigners_numbers, Foreigners_percentage, National_team_players, Stadium_name, Stadium_seats, Net_transfer_record, Coach_name, URL
- `Competitions.csv`
    - Competition_id, Name, type, country_id, country_name, domestic_league_code, confederation, URL.  
- `Games.csv` 
    - Game_id, Competition_code, Season, Round, Date, Home_club_id, Away_club_id, Home_club_goals, away_club_goals, Home_club_postions, Away_club_postion, Stadium, Attendance, Referee, URL 
- `Leagues.csv` 
    - League_id, name, Confederation
- `Player_valuations.csv` 
    - Player_id, Date, Market_value
- `Players.csv`
    - Player_id, Last_season, Current_club_id, Name, Pretty_name, country_of_birth, Country_of_citizenship, Date_of_birth, Position, Sub_position, Foot, Height_in_cm, Market_value_in_gbp, Highest_market_value_in_gbp, URL

- _What an observation consists of_: We are trying to use the variables we assume to be the most important and independent from each other. We decided on 
    - Club, Nationality, League, Appearances, Minutes, Goals, Assist, Age, Conduct, Media Presence, Years Played, Trophies, Experience, Position, Physicality, Potential. 
- _What some critical variables are, how they are represented_: We want variables which have the highest co-variance with each other. The metric should handle most features as unique features. 
- _Any special handling, transformations, cleaning, etc will be needed_: There will be club names, and probably inferences in our data. Such as Media Presence or Potential, these are metrics which can be objective to the person. How popular is the player that we are analyzing? 

We are still going to be in search of more databases that might have different descriptive data that we might like to see how organizations search for talent. We can use what they might describe as their most sought out characteristics. 

For Simplicity we can also assume that all players have no contracts for their evaluation and are based solely on performance and the other variables mentioned.

In [1]:
import pandas as pd


data = {
    name: pd.read_csv(
        file, 
        engine = 'c',
        low_memory = True,
        #memory_map = True, # set `False` to load into memory
        **kwargs
    ) for name, file, kwargs in [
        ('appearances', 'data/appearances.csv', {}),
        ('clubs', 'data/clubs.csv', {}),
        ('competitions', 'data/competitions.csv', {}),
        ('games', 'data/games.csv', {}),
        ('leagues', 'data/leagues.csv', {}),
        ('players', 'data/players.csv', {
            'parse_dates': ['date_of_birth'],
            'dtype': {
                'last_season': 'category',
                'country_of_birth': 'category',
                'country_of_citizenship': 'category',
                'position': 'category',
                'sub_position': 'category'
            }
        }),
        ('player_valuations', 'data/player_valuations.csv', {})
    ]
}

In [2]:
data['clubs'] = data['clubs'][
    ['club_id', 'name', 'total_market_value']
].rename(columns = {
    'name': 'club_name',
    'total_market_value': 'club_total_market_value'
})
data['clubs'].set_index('club_id', inplace = True)

data['clubs']

                           club_name  club_total_market_value
club_id
1032                      fc-reading                    33.66
2323                        orduspor                      NaN
1387                  acn-siena-1904                     4.32
3592              kryvbas-kryvyi-rig                     2.95
1071                  wigan-athletic                    12.38
...                              ...                      ...
1269                      pec-zwolle                    12.80
200                       fc-utrecht                    31.55
317               fc-twente-enschede                    19.04
3948     royale-union-saint-gilloise                    47.63
1304                 heracles-almelo                    15.37

[400 rows x 2 columns]

In [3]:
data['appearances'] = data['appearances'].loc[
    :, ~data['appearances'].columns.isin([
        'game_id', 
        'appearance_id', 
        'competition_id', 
        'player_club_id'
    ])
]
data['appearances'].set_index('player_id', inplace = True)

data['appearances']

           goals  assists  minutes_played  yellow_cards  red_cards
player_id
52453          0        0              90             0          0
67064          0        0              90             0          0
67064          0        0              90             0          0
67064          0        0              55             0          0
67064          0        0              90             0          0
...          ...      ...             ...           ...        ...
408574         1        0              90             0          0
408574         1        1              90             0          0
408574         0        1              27             0          0
408574         1        0              90             0          0
408574         0        0              69             0          0

[1040211 rows x 5 columns]

In [4]:
data['player_valuations'].set_index(['player_id'], inplace = True)

In [5]:
data['players'] = data['players'].loc[
    :, ~data['players'].columns.isin([
        'url', 
        'foot'
    ])
].rename(columns = {'current_club_id': 'club_id'})

data['players'].set_index('player_id', inplace = True)

data['players']

,last_season,club_id,name,pretty_name,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,height_in_cm,market_value_in_gbp,highest_market_value_in_gbp
player_id,,,,,,,,,,,,
254016,2013,855,arthur-delalande,Arthur Delalande,France,France,1992-05-18,Midfield,midfield - Central Midfield,186,NaN,90000.0
51053,2013,23,daniel-davari,Daniel Davari,Germany,Iran,1988-01-06,Goalkeeper,Goalkeeper,192,135000.0,1130000.0
31451,2013,23,torsten-oehrl,Torsten Oehrl,Germany,Germany,1986-01-07,Attack,attack - Centre-Forward,192,NaN,1130000.0
44622,2013,3691,vladimir-kisenkov,Vladimir Kisenkov,UdSSR,Russia,1981-10-08,Defender,Defender - Right-Back,182,NaN,720000.0
30802,2013,3302,oscar-diaz,Oscar Diaz,Spain,Spain,1984-04-24,Attack,attack - Centre-Forward,183,NaN,1080000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
462285,2021,200,fabian-de-keijzer,Fabian De Keijzer,Netherlands,Netherlands,2000-05-10,Goalkeeper,Goalkeeper,193,540000.0,540000.0
368612,2021,3057,merveille-bokadi,Merveille Bokadi,Zaire,DR Congo,1996-05-21,Defender,Defender - Centre-Back,186,2700000.0,3150000.0
408574,2021,383,joey-veerman,Joey Veerman,Netherlands,Netherlands,1998-11-19,Midfield,midfield - Central Midfield,185,7200000.0,7650000.0
364245,2021,383,jordan-teze,Jordan Teze,Netherlands,Netherlands,1999-09-30,Defender,Defender - Centre-Back,183,4500000.0,6750000.0
575367,2021,383,richard-ledezma,Richard Ledezma,United States,United States,2000-09-06,Attack,midfield - Attacking Midfield,174,765000.0,765000.0

In [6]:
df = data['players'].merge(
    data['player_valuations'], 
    on = 'player_id',
    copy = False
).merge(
    data['appearances'], 
    on = 'player_id',
    copy = False
).merge(
    data['clubs'], 
    on = 'club_id',
    copy = False
).drop(columns = 'club_id')

df

,last_season,name,pretty_name,country_of_birth,country_of_citizenship,date_of_birth,position,sub_position,height_in_cm,market_value_in_gbp,highest_market_value_in_gbp,date,market_value,goals,assists,minutes_played,yellow_cards,red_cards,club_name,club_total_market_value
0,2013,artem-milevskyi,Artem Milevskyi,UdSSR,Ukraine,1985-01-12,Attack,attack - Centre-Forward,189,NaN,9900000.0,2004-10-04,225000,0,2,86,0,0,gaziantepspor,NaN
1,2013,artem-milevskyi,Artem Milevskyi,UdSSR,Ukraine,1985-01-12,Attack,attack - Centre-Forward,189,NaN,9900000.0,2004-10-04,225000,0,0,86,0,0,gaziantepspor,NaN
2,2013,artem-milevskyi,Artem Milevskyi,UdSSR,Ukraine,1985-01-12,Attack,attack - Centre-Forward,189,NaN,9900000.0,2004-10-04,225000,0,0,86,0,0,gaziantepspor,NaN
3,2013,artem-milevskyi,Artem Milevskyi,UdSSR,Ukraine,1985-01-12,Attack,attack - Centre-Forward,189,NaN,9900000.0,2004-10-04,225000,0,0,59,0,0,gaziantepspor,NaN
4,2013,artem-milevskyi,Artem Milevskyi,UdSSR,Ukraine,1985-01-12,Attack,attack - Centre-Forward,189,NaN,9900000.0,2004-10-04,225000,0,0,68,0,0,gaziantepspor,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23386683,2021,cameron-puertas,Cameron Puertas,Switzerland,Spain,1998-08-18,Midfield,midfield - Central Midfield,178,1530000.0,1800000.0,2022-04-12,1530000,0,0,19,0,0,royale-union-saint-gilloise,47.63
23386684,2021,cameron-puertas,Cameron Puertas,Switzerland,Spain,1998-08-18,Midfield,midfield - Central Midfield,178,1530000.0,1800000.0,2022-04-12,1530000,0,0,4,1,0,royale-union-saint-gilloise,47.63
23386685,2021,cameron-puertas,Cameron Puertas,Switzerland,Spain,1998-08-18,Midfield,midfield - Central Midfield,178,1530000.0,1800000.0,2022-04-12,1530000,0,0,3,0,0,royale-union-saint-gilloise,47.63
23386686,2021,cameron-puertas,Cameron Puertas,Switzerland,Spain,1998-08-18,Midfield,midfield - Central Midfield,178,1530000.0,1800000.0,2022-04-12,1530000,0,0,45,0,0,royale-union-saint-gilloise,47.63
23386687,2021,cameron-puertas,Cameron Puertas,Switzerland,Spain,1998-08-18,Midfield,midfield - Central Midfield,178,1530000.0,1800000.0,2022-04-12,1530000,0,0,4,0,0,royale-union-saint-gilloise,47.63

In [7]:
df.dtypes

last_season                          category
name                                   object
pretty_name                            object
country_of_birth                     category
country_of_citizenship               category
date_of_birth                  datetime64[ns]
position                             category
sub_position                         category
height_in_cm                            int64
market_value_in_gbp                   float64
highest_market_value_in_gbp           float64
date                                   object
market_value                            int64
goals                                   int64
assists                                 int64
minutes_played                          int64
yellow_cards                            int64
red_cards                               int64
club_name                              object
club_total_market_value               float64
dtype: object

In [8]:
df.describe()

,height_in_cm,market_value_in_gbp,highest_market_value_in_gbp,market_value,goals,assists,minutes_played,yellow_cards,red_cards,club_total_market_value
count,2.338669e+07,2.037661e+07,2.338669e+07,2.338669e+07,2.338669e+07,2.338669e+07,2.338669e+07,2.338669e+07,2.338669e+07,2.298890e+07
mean,1.815418e+02,5.700252e+06,1.226523e+07,5.338843e+06,1.037175e-01,7.772768e-02,7.167880e+01,1.513089e-01,3.589991e-03,1.541642e+02
std,1.315948e+01,1.162233e+07,1.858048e+07,1.081278e+07,3.462880e-01,2.898990e-01,2.868347e+01,3.696840e-01,5.980889e-02,1.982415e+02
min,0.000000e+00,9.000000e+03,9.000000e+03,9.000000e+03,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.100000e+00
25%,1.780000e+02,3.600000e+05,1.800000e+06,4.500000e+05,0.000000e+00,0.000000e+00,6.100000e+01,0.000000e+00,0.000000e+00,1.960000e+01
50%,1.830000e+02,1.350000e+06,5.400000e+06,1.350000e+06,0.000000e+00,0.000000e+00,9.000000e+01,0.000000e+00,0.000000e+00,7.414000e+01
75%,1.870000e+02,4.500000e+06,1.440000e+07,5.400000e+06,0.000000e+00,0.000000e+00,9.000000e+01,0.000000e+00,0.000000e+00,2.187900e+02
max,2.060000e+02,1.440000e+08,1.800000e+08,1.800000e+08,6.000000e+00,6.000000e+00,1.200000e+02,2.000000e+00,1.000000e+00,8.633700e+02

# Proposed Solution

<blockquote>
In this section, clearly describe a solution to the problem. The solution should be applicable to the project domain and appropriate for the dataset(s) or input(s) given. Provide enough detail (e.g., algorithmic description and/or theoretical properties) to convince us that your solution is applicable. Make sure to describe how the solution will be tested.  

If you know details already, describe how (e.g., library used, function calls) you plan to implement the solution in a way that is reproducible.

If it is appropriate to the problem statement, describe a benchmark model<a name="sota"></a>[<sup>[3]</sup>](#sotanote) against which your solution will be compared. 
    
> I would recommend using sklearn or statsmodels in python for ordinary least squares rather than numpy. You will find a better ecosystem to help you understand your model.
What are you planning to use tensorflow for?
I like that your team is thinking about preprocessing techniques.    
</blockquote>











Packages: 
- `sklearn` (scikit-learn)
- `tensorflow` (TensorFlow)
- Least square regression: `numpy.linalg.lstsq`

We believe that we can take the characteristics football clubs may regard to be the most important in the dataset and use those features to evaluate players. Those can be our core information in order to use regression analysis. If able to determine a certain cluster for the data set depending on the position and attributes. We can compare the players in the data set with the new data. We will be using OLS (Ordinary Least Squares).  

We have to start with the most important step which is data cleaning and EDA analysis in order to get more accurate results, Matrix transformation with the numpy library. In order to increase covariance with variables, we can use dimension reduction techniques. Next we can normalize the data sets in order to not get skewed by one particular feature. Dealing with values missing or if we need to have numeric values for non-numeric data (i.e popularity, health, position).

Our comparison of errors will be coming from the Transfermrket.com website as it is updated everyday to evaluate different players. We can get the player’s information to get a percent error or a total error for our evaluations. If we can, we will use the RMSE (Root mean square error) or Mean Absolute Values of our model prediction.

# Evaluation Metrics
<blockquote>
Propose at least one evaluation metric that can be used to quantify the performance of both the benchmark model and the solution model. The evaluation metric(s) you propose should be appropriate given the context of the data, the problem statement, and the intended solution. Describe how the evaluation metric(s) are derived and provide an example of their mathematical representations (if applicable). Complex evaluation metrics should be clearly defined and quantifiable (can be expressed in mathematical or logical terms).

> RMSE is a good metric here. It will tell you a very interpretable value: Euros!
I am not sure what you are going to use euclidean distance for.

</blockquote>


We will be using an OLS regression model and the evaluation techniques we are considering are RMSE and Euclidean distance.
A possible evaluation metric we will use is RMSE or Mean Absolute Value of Errors. It is derived by calculating the difference between the estimated and actual value, square those results, then calculate the mean of those results. The formula for RMSE is 

$$
    \text{RMSE} = \sqrt{\frac{\sum_{i = 1}^{N}\left(\text{Predicted}_{i} - \text{Actual}_{i}\right)^{2}}{N}}
$$

The formula for Euclidean Distance is 
$$
    d(p, q)={\sqrt{(q_{1} - p_{1})^{2} + (q_{2} - p_{2})^{2}}}
$$

And it allows us to find the distance between two points which will give us the similarity of the two points.

# Preliminary results

<blockquote>
NEW SECTION!

Please show any preliminary results you have managed to obtain.

Examples would include:
- Analyzing the suitability of a dataset or alogrithm for prediction/solving your problem 
- Performing feature selection or hand-designing features from the raw data. Describe the features available/created and/or show the code for selection/creation
- Showing the performance of a base model/hyper-parameter setting.  Solve the task with one "default" algorithm and characterize the performance level of that base model.
- Learning curves or validation curves for a particular model
- Tables/graphs showing the performance of different models/hyper-parameters
</blockquote>


TODO

# Ethics & Privacy

<blockquote>
If your project has obvious potential concerns with ethics or data privacy discuss that here.  Almost every ML project put into production can have ethical implications if you use your imagination. Use your imagination.

Even if you can't come up with an obvious ethical concern that should be addressed, you should know that a large number of ML projects that go into producation have unintended consequences and ethical problems once in production. How will your team address these issues?

Consider a tool to help you address the potential issues such as https://deon.drivendata.org
</blockquote>



Since our data is readily available to the public and conforms to the privacy policy of the sourcing website Transfermarkt, we believe our research will not be subject to immediate concerns with neither ethics nor data privacy. Variables include `name`/`pretty_name` (name), `country_of_birth`/`country_of_citizenship` (nationality), `date_of_birth` (age) might be potentially relevant but are in no way detrimental to the ethics of our research. However, we do believe that the result of our research, once obtained and made public, could have unintended consequences. We evaluate a player's performance solely based on historical data; this implies that there will be biases. It is reasonable to expect that those biases, if not addressed and handled properly, could cause permanent damage to a person’s career. For instance, if a reliable player’s record shows that the player is unreliable, then team recruiters would use that information to make an informed decision based on false information. To prevent the chance of this being a consequence, we will put a disclaimer regarding the features that were not used in the evaluation of a player’s value. If a problem such as this comes up, we will remove said player's data from the study and make an effort to find and use the accurate data for each player.

# Team Expectations

<blockquote>
Put things here that cement how you will interact/communicate as a team, how you will handle conflict and difficulty, how you will handle making decisions and setting goals/schedule, how much work you expect from each other, how you will handle deadlines, etc...
* *Team Expectation 1*
* *Team Expectation 2*
* *Team Expecation 3*
* ...
    
> I recommend you clearly assign responsibilities, but this looks like a good set of principles.

</blockquote>



- Show up to meetings on time and actively participate
- Handle conflict and difficulty professionally
- Make constructive decisions and criticisms
- Work collaboratively and inclusively with all team members
- Communicate with the whole team regularly to finalize ideas

# Project Timeline Proposal

<blockquote>

UPDATE THE PROPOSAL TIMELINE ACCORDING TO WHAT HAS ACTUALLY HAPPENED AND HOW IT HAS EFFECTED YOUR FUTURE PLANS

> I recommend you dedicate specific time to model selection and evaluate multiple models (even if that is just the same model class with different hyper-params).
</blockquote>


| Meeting Date | Meeting Time | Completed Before Meeting | Discuss at Meeting |
|:---:|:---:|:---:|:---:|
| 4/22 | 3:30 PM | Brainstorm topics/questions (all) | Determine best form of communication; Discuss and decide on final project topic; which dataset would be most ideal, discuss hypothesis; begin background research. |
|  4/24 | 3:30 PM | Complete Draft for Proposal | Finish Proposal. Discussion on potential ML techniques. Submit Proposal. |
| 4/27 | 3 PM | Do background research on topic  | Discuss ideal dataset(s) and ethics; draft project proposal |
| 5/2 | 3 PM | Edit, finalize, and submit proposal; Search for datasets  | Discuss Wrangling and possible analytical approaches; Assign group members to lead each specific part |
| 5/13 | 3 PM | Import & Wrangle Data, do some EDA  | Review/Edit wrangling/EDA; Discuss Analysis Plan |
| 5/20 | 3 PM | Import & Wrangle Data, do some EDA  | Review/Edit wrangling/EDA; Discuss Analysis Plan |
| 5/25 | 3 PM | Finalize wrangling/EDA; Begin programming for project  | Discuss/edit project code; Complete project |
| 5/30 | 3 PM | Complete analysis; Draft results/conclusion/discussion  | Discuss/edit full project |
| 6/8 | Before 11:59 PM | N/A | Turn in Final Project |

# Footnotes

<sup><a name="assoc-football" href="#note-assoc-football">1</a></sup> Wikipedia contributors. (2022, April 24). *Association football.* Wikipedia. https://en.wikipedia.org/wiki/Association_football

<sup><a name="transfermarkt-value-how" href="#note-transfermarkt-value-how">2</a></sup> Biswas, B. (2021, July 16). Transfermarkt Market Value explained - How is it determined? *Transfermarkt.* https://www.transfermarkt.co.in/transfermarkt-market-value-explained-how-is-it-determined-/view/news/385100

<sup><a name="peeters" href="#note-peeters">3</a></sup> Peeters, T. (2018). Testing the Wisdom of Crowds in the field: Transfermarkt valuations and international soccer results. *International Journal of Forecasting*, 34(1), 17–29. https://doi.org/10.1016/j.ijforecast.2017.08.002

<sup><a name="ackermann-follert-etal" href="#note-ackermann-follert-etal">4</a></sup>
Ackermann, P., & Follert, F. (2018). *Einige bewertungstheoretische Anmerkungen zur Marktwertanalyse der Plattform transfermarkt.de.* doi:10.22028/D291-32113

<sup><a name="transfermarkt-de" href="#note-transfermarkt-de">5</a></sup> Transfermarkt. (2000, May). *Fußball-Transfers, Gerüchte, Marktwerte und News.* https://www.transfermarkt.de/

<sup><a name="man-utd" href="#note-man-utd">6</a></sup> Summerscales, R. (2022, February 7). Man Utd, Man City And PSG Have Each Spent Over $1Billion Net On Transfers In 10 Years. *Futbol on FanNation.* https://www.si.com/fannation/soccer/futbol/news/man-utd-city-and-psg-spend-over-1b-net-on-transfers-in-10-years

<sup><a name="cariboo" href="#note-cariboo">7</a></sup> *Football Data from Transfermarkt.* (2022, April 22). [Dataset]. https://www.kaggle.com/datasets/davidcariboo/player-scores